name: Linux CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build the test image
        run: docker build -t popt -f ci/Dockerfile .
      - name: Run the test suite
        run: docker run -t popt
